# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tv_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(240, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.volumeUp = QtWidgets.QPushButton(self.centralwidget)
        self.volumeUp.setGeometry(QtCore.QRect(200, 100, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.volumeUp.setFont(font)
        self.volumeUp.setObjectName("volumeUp")
        self.volumeDown = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDown.setGeometry(QtCore.QRect(200, 200, 88, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeDown.sizePolicy().hasHeightForWidth())
        self.volumeDown.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.volumeDown.setFont(font)
        self.volumeDown.setObjectName("volumeDown")
        self.channelUp = QtWidgets.QPushButton(self.centralwidget)
        self.channelUp.setGeometry(QtCore.QRect(10, 100, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.channelUp.setFont(font)
        self.channelUp.setObjectName("channelUp")
        self.channelDown = QtWidgets.QPushButton(self.centralwidget)
        self.channelDown.setGeometry(QtCore.QRect(10, 200, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.channelDown.setFont(font)
        self.channelDown.setObjectName("channelDown")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 340, 256, 192))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerButton.setText(_translate("MainWindow", "°"))
        self.volumeUp.setText(_translate("MainWindow", "+"))
        self.volumeDown.setText(_translate("MainWindow", "-"))
        self.channelUp.setText(_translate("MainWindow", "CH+"))
        self.channelDown.setText(_translate("MainWindow", "CH+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
