# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tv_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Remote(object):
    def setupUi(self, Remote):
        Remote.setObjectName("Remote")
        Remote.resize(300, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Remote.sizePolicy().hasHeightForWidth())
        Remote.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Remote)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QPushButton(self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(240, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.volumeUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.volumeUpButton.setGeometry(QtCore.QRect(200, 100, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.volumeUpButton.setFont(font)
        self.volumeUpButton.setObjectName("volumeUpButton")
        self.volumeDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.volumeDownButton.setGeometry(QtCore.QRect(200, 200, 88, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeDownButton.sizePolicy().hasHeightForWidth())
        self.volumeDownButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.volumeDownButton.setFont(font)
        self.volumeDownButton.setObjectName("volumeDownButton")
        self.channelUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.channelUpButton.setGeometry(QtCore.QRect(10, 100, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.channelUpButton.setFont(font)
        self.channelUpButton.setObjectName("channelUpButton")
        self.channelDownButton = QtWidgets.QPushButton(self.centralwidget)
        self.channelDownButton.setGeometry(QtCore.QRect(10, 200, 88, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.channelDownButton.setFont(font)
        self.channelDownButton.setObjectName("channelDownButton")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 340, 256, 192))
        self.listView.setObjectName("listView")
        Remote.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Remote)
        self.statusbar.setObjectName("statusbar")
        Remote.setStatusBar(self.statusbar)

        self.retranslateUi(Remote)
        QtCore.QMetaObject.connectSlotsByName(Remote)

    def retranslateUi(self, Remote):
        _translate = QtCore.QCoreApplication.translate
        Remote.setWindowTitle(_translate("Remote", "MainWindow"))
        self.powerButton.setText(_translate("Remote", "°"))
        self.volumeUpButton.setText(_translate("Remote", "+"))
        self.volumeDownButton.setText(_translate("Remote", "-"))
        self.channelUpButton.setText(_translate("Remote", "CH+"))
        self.channelDownButton.setText(_translate("Remote", "CH+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Remote = QtWidgets.QMainWindow()
    ui = Ui_Remote()
    ui.setupUi(Remote)
    Remote.show()
    sys.exit(app.exec_())
